###channel-artifacts is no room to place, however bind it to the orderer is an good idea

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: $namespace
  name: $podName
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        org: $namespace
        orderer-id: $ordererID
    spec:      
      containers:
      - name: $podName
        image: hyperledger/fabric-orderer:x86_64-$version
        env:
        # - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
        #   value: cbr0
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: $localMSPID
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "$tlsEnabled"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
         - containerPort: 7050
        command: ["orderer"]
        volumeMounts:
         - mountPath: /var/hyperledger/orderer/msp 
           name: certificate
           #subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
           # subPath: $mspPath
         - mountPath: /var/hyperledger/orderer/tls
           name: tlscertificate
           #subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/
           # subPath: $tlsPath
         - mountPath: /var/hyperledger/orderer/orderer.genesis.block
           name: genesis
           # subPath: genesis.block
         # - mountPath: /var/hyperledger/production/orderer
         #   name: data
      volumes:
        - name: certificate
          hostPath:
            path: $path/msp
        - name: tlscertificate
          hostPath:
            path: $path/tls
        - name: genesis
          hostPath:
            path: $genesis/genesis.block
        - name: data
          hostPath:
            # path: $shareFolder/orderer/$namespace/$ordererID
            path: /data/orderer/$namespace/$ordererID
         # persistentVolumeClaim:
             # claimName: $pvName
           #path: $shareFolder
         #persistentVolumeClaim:
         #  claimName: nfs


---
apiVersion: v1
kind: Service
metadata:
  name: $ordererID
  namespace: $namespace
spec:
 selector:
   app: hyperledger
   role: orderer
   orderer-id: $ordererID
   org: $namespace
 type: NodePort
 # type: ClusterIP
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: 7050
     targetPort: 7050
     nodePort: $nodePort
