Tenant: f-1

OrdererOrgs:
  - Name: Orderer
    Domain: orgorderer 
    Template:
      Count: 1

PeerOrgs:
  - Name: Org1
    Domain: org1
    Template:
      Count: 1
    Users:
      Count: 0
  # - Name: Org2
  #   Domain: org2
  #   Template:
  #     Count: 1
  #   Users:
  #     Count: 0
  # - Name: Org3
  #   Domain: org3
  #   Template:
  #     Count: 3
  #   Users:
  #     Count: 1
