Profiles:
  MultiOrgsChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
      - Name: Idp1MSP
        ID: Idp1MSP
        MSPDir: crypto-config/peerOrganizations/idp1-v1/msp
        AnchorPeers:
        - Host: peer0.idp1-v1
          Port: 7051
      - Name: Idp2MSP
        ID: Idp2MSP
        MSPDir: crypto-config/peerOrganizations/idp2-v1/msp
        AnchorPeers:
        - Host: peer0.idp2-v1
          Port: 7051
      - Name: Idp3MSP
        ID: Idp3MSP
        MSPDir: crypto-config/peerOrganizations/idp3-v1/msp
        AnchorPeers:
        - Host: peer0.idp3-v1
          Port: 7051
      - Name: As1MSP
        ID: As1MSP
        MSPDir: crypto-config/peerOrganizations/as1-v1/msp
        AnchorPeers:
        - Host: peer0.as1-v1
          Port: 7051
      - Name: As2MSP
        ID: As2MSP
        MSPDir: crypto-config/peerOrganizations/as2-v1/msp
        AnchorPeers:
        - Host: peer0.as2-v1
          Port: 7051
      - Name: Rp1MSP
        ID: Rp1MSP
        MSPDir: crypto-config/peerOrganizations/rp1-v1/msp
        AnchorPeers:
        - Host: peer0.rp1-v1
          Port: 7051
  MultiOrgsOrdererGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
      - orderer0.orgorderer-v1:7050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 103809024
        PreferredMaxBytes: 524288
      Organizations:
      - Name: OrdererOrg
        ID: Orderer0MSP
        MSPDir: crypto-config/ordererOrganizations/orgorderer-v1/msp
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: Idp1MSP
          ID: Idp1MSP
          MSPDir: crypto-config/peerOrganizations/idp1-v1/msp
          AnchorPeers:
          - Host: peer0.idp1-v1
            Port: 7051
        - Name: Idp2MSP
          ID: Idp2MSP
          MSPDir: crypto-config/peerOrganizations/idp2-v1/msp
          AnchorPeers:
          - Host: peer0.idp2-v1
            Port: 7051
        - Name: Idp3MSP
          ID: Idp3MSP
          MSPDir: crypto-config/peerOrganizations/idp3-v1/msp
          AnchorPeers:
          - Host: peer0.idp3-v1
            Port: 7051
        - Name: As1MSP
          ID: As1MSP
          MSPDir: crypto-config/peerOrganizations/as1-v1/msp
          AnchorPeers:
          - Host: peer0.as1-v1
            Port: 7051
        - Name: As2MSP
          ID: As2MSP
          MSPDir: crypto-config/peerOrganizations/as2-v1/msp
          AnchorPeers:
          - Host: peer0.as2-v1
            Port: 7051
        - Name: Rp1MSP
          ID: Rp1MSP
          MSPDir: crypto-config/peerOrganizations/rp1-v1/msp
          AnchorPeers:
          - Host: peer0.rp1-v1
            Port: 7051
Organizations:
- Name: OrdererOrg
  ID: Orderer0MSP
  MSPDir: crypto-config/ordererOrganizations/orgordererv1/msp
- Name: Idp1MSP
  ID: Idp1MSP
  MSPDir: crypto-config/peerOrganizations/idp1-v1/msp
  AnchorPeers:
  - Host: peer0.idp1-v1
    Port: 7051
- Name: Idp2MSP
  ID: Idp2MSP
  MSPDir: crypto-config/peerOrganizations/idp2-v1/msp
  AnchorPeers:
  - Host: peer0.idp2-v1
    Port: 7051
- Name: Idp3MSP
  ID: Idp3MSP
  MSPDir: crypto-config/peerOrganizations/idp3-v1/msp
  AnchorPeers:
  - Host: peer0.idp3-v1
    Port: 7051
- Name: As1MSP
  ID: As1MSP
  MSPDir: crypto-config/peerOrganizations/as1-v1/msp
  AnchorPeers:
  - Host: peer0.as1-v1
    Port: 7051
- Name: As2MSP
  ID: As2MSP
  MSPDir: crypto-config/peerOrganizations/as2-v1/msp
  AnchorPeers:
  - Host: peer0.as2-v1
    Port: 7051
- Name: Rp1MSP
  ID: Rp1MSP
  MSPDir: crypto-config/peerOrganizations/rp1-v1/msp
  AnchorPeers:
  - Host: peer0.rp1-v1
    Port: 7051
Orderer:
  OrdererType: solo
  Addresses:
  - orderer0.orgorderer-v1:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 103809024
    PreferredMaxBytes: 524288
  Organizations:
  - Name: OrdererOrg
    ID: Orderer0MSP
    MSPDir: crypto-config/ordererOrganizations/orgorderer-v1/msp
