Profiles:
  MultiOrgsChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
      - Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1-v1/msp
        AnchorPeers:
        - Host: peer0.org1-v1
          Port: 7051
  MultiOrgsOrdererGenesis:
    Orderer:
      OrdererType: kafka
      Addresses:
      - orderer0.orgorderer-v1:7050
      - orderer1.orgorderer-v1:7050
      - orderer2.orgorderer-v1:7050
      BatchTimeout: 2s
      BatchSize:
        AbsoluteMaxBytes: 103809024
        PreferredMaxBytes: 524288
      Kafka:
        Brokers:
        - kafka0.kafka:9092
        - kafka1.kafka:9092
        - kafka2.kafka:9092
        - kafka3.kafka:9092
      Organizations:
      - Name: OrdererOrg
        ID: Orderer0MSP
        MSPDir: crypto-config/ordererOrganizations/orgorderer-v1/msp
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: Org1MSP
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/org1-v1/msp
          AnchorPeers:
          - Host: peer0.org1-v1
            Port: 7051
Organizations:
- Name: OrdererOrg
  ID: Orderer0MSP
  MSPDir: crypto-config/ordererOrganizations/orgordererv1/msp
- Name: Org1MSP
  ID: Org1MSP
  MSPDir: crypto-config/peerOrganizations/org1-v1/msp
  AnchorPeers:
  - Host: peer0.org1-v1
    Port: 7051
Orderer:
  OrdererType: kafka
  Addresses:
  - orderer0.orgorderer-v1:7050
  - orderer1.orgorderer-v1:7050
  - orderer2.orgorderer-v1:7050
  BatchTimeout: 2s
  BatchSize:
    AbsoluteMaxBytes: 103809024
    PreferredMaxBytes: 524288
  Kafka:
    Brokers:
    - kafka0.kafka:9092
    - kafka1.kafka:9092
    - kafka2.kafka:9092
    - kafka3.kafka:9092
  Organizations:
  - Name: OrdererOrg
    ID: Orderer0MSP
    MSPDir: crypto-config/ordererOrganizations/orgorderer-v1/msp
