Profiles:
  MultiOrgsChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
      - Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1-f-1/msp
        AnchorPeers:
        - Host: peer0.org1-f-1
          Port: 7051
  OneOrgOrdererGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
      - orderer0.orgorderer-f-1:7050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 103809024
        PreferredMaxBytes: 524288
      Organizations:
      - Name: OrdererOrg
        ID: Orderer0MSP
        MSPDir: crypto-config/ordererOrganizations/orgorderer-f-1/msp
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: Org1MSP
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/org1-f-1/msp
          AnchorPeers:
          - Host: peer0.org1-f-1
            Port: 7051
Organizations:
- Name: OrdererOrg
  ID: Orderer0MSP
  MSPDir: crypto-config/ordererOrganizations/orgordererf-1/msp
- Name: Org1MSP
  ID: Org1MSP
  MSPDir: crypto-config/peerOrganizations/org1-f-1/msp
  AnchorPeers:
  - Host: peer0.org1-f-1
    Port: 7051
Orderer:
  OrdererType: solo
  Addresses:
  - orderer0.orgorderer-f-1:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 103809024
    PreferredMaxBytes: 524288
  Organizations:
  - Name: OrdererOrg
    ID: Orderer0MSP
    MSPDir: crypto-config/ordererOrganizations/orgorderer-f-1/msp
